/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleCaixa;
import java.awt.Color;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Caixa;
import model.Usuario;
import net.sf.jasperreports.engine.JRException;
import util.Conversoes;
import util.LimitText;

/**
 *
 * @author Abner
 */
public class CaixaForm extends javax.swing.JDialog {

    private int xMouse, yMouse;
    private Caixa p = new Caixa();
    private ControleCaixa cc = new ControleCaixa();
    private ArrayList<Caixa> listaPesquisa = new ArrayList();
    private Caixa selecionado;
    private int menuSelection = 0;
    private Color errorColor = new Color(255, 0, 0);

    public CaixaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        warningPanelForm.setVisible(false);
        warningPanelData.setVisible(false);
        atualizaTabela();
        tableUsuarios.getTableHeader().setBackground(new Color(51, 51, 51));
        tableUsuarios.getTableHeader().setForeground(new Color(255, 255, 255));
    }

    private void atualizaTabela() {
        new Thread() {
            @Override
            public void run() {
                listaPesquisa.clear();
                listaPesquisa.addAll(cc.findByDatas(txtData1.getText(), txtData2.getText()));
                DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();
                dtm.setNumRows(0);
                for (Caixa s : listaPesquisa) {
                    dtm.addRow(new Object[]{Conversoes.getDateToString(s.getAbertura()), s.getEntradas(), s.getSaidas()});
                }
            }
        }.start();
    }

    private void setCaixa() {
        txtInicial.setText(Double.toString(selecionado.getSaldoInicial()));
        txtEntradas.setText(Double.toString(selecionado.getEntradas()));
        txtSaidas.setText(Double.toString(selecionado.getSaidas()));
        txtAbertura.setText(Conversoes.getDatetimeToString(selecionado.getAbertura()));
        txtUsuario.setText(selecionado.getUsuario().getNome());
        if (selecionado.getFechamento() == null) {
            txtFechamento.setText(Conversoes.getDatetimeToString(new Date()));
        } else {
            txtFechamento.setText(Conversoes.getDatetimeToString(selecionado.getFechamento()));
        }

    }

    private void limparCampos() {
        txtFechamento.setText("");
        txtAbertura.setText("");
        txtEntradas.setText("");
        txtSaidas.setText("");
        txtUsuario.setText("");
        txtInicial.setText("");
        txtFinal.setText("");

        selecionado = null;
    }

    private void voltar() {
        menuSelection = 0;
        btnRelatorio.unselect();
        btnFechar.unselect();
        btnVisualizar.unselect();
        limparCampos();
        dataPanel.setVisible(true);
        formPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRelatorio = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnFechar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        btnVisualizar = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        cardPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        warningPanelData = new javax.swing.JPanel();
        btnMessage = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningData = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        mGradientButton1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        txtData1 = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtData2 = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        tablePanel = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        btnExit = new com.hq.swingmaterialdesign.materialdesign.MButton();
        formPanel = new javax.swing.JPanel();
        warningPanelForm = new javax.swing.JPanel();
        btnError = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mButton4 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtFechamento = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        botCancelar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botConfirmar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtUsuario = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtFinal = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtInicial = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtAbertura = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtEntradas = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtSaidas = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bgMouseReleased(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(24, 24, 24));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Mont SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUÁRIO");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 230, 40));

        btnRelatorio.setBackground(new java.awt.Color(24, 24, 24));
        btnRelatorio.setBorder(null);
        btnRelatorio.setText("Gerar relatório");
        btnRelatorio.setEndColor(new java.awt.Color(24, 24, 24));
        btnRelatorio.setFont(new java.awt.Font("Mont Bold", 0, 14)); // NOI18N
        btnRelatorio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnRelatorio.setHoverEndColor(new java.awt.Color(24, 24, 24));
        btnRelatorio.setHoverStartColor(new java.awt.Color(37, 46, 55));
        btnRelatorio.setSelectedColor(new java.awt.Color(50, 56, 68));
        btnRelatorio.setStartColor(new java.awt.Color(24, 24, 24));
        btnRelatorio.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        sidePanel.add(btnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 230, 50));

        btnFechar.setBackground(new java.awt.Color(24, 24, 24));
        btnFechar.setBorder(null);
        btnFechar.setText("Fechar caixa");
        btnFechar.setEndColor(new java.awt.Color(24, 24, 24));
        btnFechar.setFont(new java.awt.Font("Mont Bold", 0, 14)); // NOI18N
        btnFechar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnFechar.setHoverEndColor(new java.awt.Color(24, 24, 24));
        btnFechar.setHoverStartColor(new java.awt.Color(37, 46, 55));
        btnFechar.setSelectedColor(new java.awt.Color(50, 56, 68));
        btnFechar.setStartColor(new java.awt.Color(24, 24, 24));
        btnFechar.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        sidePanel.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 50));

        btnVisualizar.setBackground(new java.awt.Color(24, 24, 24));
        btnVisualizar.setBorder(null);
        btnVisualizar.setText("Visualizar");
        btnVisualizar.setEndColor(new java.awt.Color(24, 24, 24));
        btnVisualizar.setFont(new java.awt.Font("Mont Bold", 0, 14)); // NOI18N
        btnVisualizar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVisualizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnVisualizar.setHoverEndColor(new java.awt.Color(24, 24, 24));
        btnVisualizar.setHoverStartColor(new java.awt.Color(37, 46, 55));
        btnVisualizar.setSelectedColor(new java.awt.Color(50, 56, 68));
        btnVisualizar.setStartColor(new java.awt.Color(24, 24, 24));
        btnVisualizar.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        sidePanel.add(btnVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 230, 50));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 580));

        cardPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setBackground(new java.awt.Color(51, 51, 51));
        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelData.setBackground(new java.awt.Color(0, 153, 0));

        btnMessage.setBackground(new java.awt.Color(0, 153, 0));
        btnMessage.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnMessage.setBorderRadius(0);
        btnMessage.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnMessage.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageActionPerformed(evt);
            }
        });

        labelWarningData.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningData.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningData.setText("Cadastro efetuado com sucesso.");

        javax.swing.GroupLayout warningPanelDataLayout = new javax.swing.GroupLayout(warningPanelData);
        warningPanelData.setLayout(warningPanelDataLayout);
        warningPanelDataLayout.setHorizontalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelDataLayout.createSequentialGroup()
                .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelDataLayout.setVerticalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataPanel.add(warningPanelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        searchPanel.setBackground(new java.awt.Color(24, 24, 24));

        mGradientButton1.setForeground(new java.awt.Color(204, 204, 204));
        mGradientButton1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        mGradientButton1.setBorderRadius(58);
        mGradientButton1.setEndColor(new java.awt.Color(24, 24, 24));
        mGradientButton1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        mGradientButton1.setHoverEndColor(new java.awt.Color(24, 24, 24));
        mGradientButton1.setHoverStartColor(new java.awt.Color(24, 24, 24));
        mGradientButton1.setStartColor(new java.awt.Color(24, 24, 24));
        mGradientButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseExited(evt);
            }
        });
        mGradientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton1ActionPerformed(evt);
            }
        });

        txtData1.setBackground(new java.awt.Color(24, 24, 24));
        txtData1.setForeground(new java.awt.Color(240, 240, 240));
        txtData1.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtData1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData1.setLabel("Data Inicial");
        txtData1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtData1FocusGained(evt);
            }
        });

        txtData2.setBackground(new java.awt.Color(24, 24, 24));
        txtData2.setForeground(new java.awt.Color(240, 240, 240));
        txtData2.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtData2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData2.setLabel("Data Final");
        txtData2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtData2FocusGained(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtData1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        dataPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 100));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePanel.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tablePanel.setHorizontalScrollBar(null);

        tableUsuarios.setBackground(new java.awt.Color(51, 51, 51));
        tableUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableUsuarios.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tableUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Entradas", "Saídas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        tableUsuarios.setRowHeight(30);
        tableUsuarios.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tableUsuarios.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablePanel.setViewportView(tableUsuarios);
        tableUsuarios.getTableHeader().setFont(new java.awt.Font("Nunito Bold", 0, 14));

        dataPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 670, 390));

        btnExit.setBackground(new java.awt.Color(51, 51, 51));
        btnExit.setBorder(null);
        btnExit.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit.setBorderRadius(0);
        btnExit.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        dataPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 40));

        cardPanel.add(dataPanel, "card2");

        formPanel.setBackground(new java.awt.Color(51, 51, 51));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm.setBackground(new java.awt.Color(255, 51, 51));

        btnError.setBackground(new java.awt.Color(255, 51, 51));
        btnError.setBorder(null);
        btnError.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError.setBorderRadius(0);
        btnError.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorActionPerformed(evt);
            }
        });

        labelWarningForm.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm.setText("Preencha os campos corretamente.");

        javax.swing.GroupLayout warningPanelFormLayout = new javax.swing.GroupLayout(warningPanelForm);
        warningPanelForm.setLayout(warningPanelFormLayout);
        warningPanelFormLayout.setHorizontalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelFormLayout.createSequentialGroup()
                .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelFormLayout.setVerticalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanel.add(warningPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        mButton4.setBackground(new java.awt.Color(102, 102, 102));
        mButton4.setBorder(null);
        mButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton4.setBorderRadius(0);
        mButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton4.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton4MouseExited(evt);
            }
        });
        mButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        txtFechamento.setEditable(false);
        txtFechamento.setBackground(new java.awt.Color(51, 51, 51));
        txtFechamento.setForeground(new java.awt.Color(240, 240, 240));
        txtFechamento.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtFechamento.setLabel("Horário de Fechamento");
        txtFechamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechamentoFocusGained(evt);
            }
        });
        txtFechamento.setDocument(new LimitText(50));
        formPanel.add(txtFechamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 260, 51));

        botCancelar.setBackground(new java.awt.Color(102, 102, 102));
        botCancelar.setBorder(null);
        botCancelar.setText("CANCELAR");
        botCancelar.setBorderRadius(50);
        botCancelar.setFont(new java.awt.Font("Mont Bold", 0, 14)); // NOI18N
        botCancelar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        formPanel.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 514, 180, 50));

        botConfirmar.setBackground(new java.awt.Color(153, 153, 153));
        botConfirmar.setBorder(null);
        botConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        botConfirmar.setText("Confirmar");
        botConfirmar.setBorderRadius(50);
        botConfirmar.setFont(new java.awt.Font("Mont Bold", 0, 14)); // NOI18N
        botConfirmar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarActionPerformed(evt);
            }
        });
        formPanel.add(botConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 514, 180, 50));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(51, 51, 51));
        txtUsuario.setForeground(new java.awt.Color(240, 240, 240));
        txtUsuario.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtUsuario.setLabel("Usuário");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
        });
        txtFechamento.setDocument(new LimitText(50));
        formPanel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 260, 51));

        txtFinal.setEditable(false);
        txtFinal.setBackground(new java.awt.Color(51, 51, 51));
        txtFinal.setForeground(new java.awt.Color(240, 240, 240));
        txtFinal.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtFinal.setLabel("Saldo Final");
        txtFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFinalFocusGained(evt);
            }
        });
        formPanel.add(txtFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 260, 51));

        txtInicial.setEditable(false);
        txtInicial.setBackground(new java.awt.Color(51, 51, 51));
        txtInicial.setForeground(new java.awt.Color(240, 240, 240));
        txtInicial.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtInicial.setLabel("Saldo Inicial");
        txtInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInicialFocusGained(evt);
            }
        });
        formPanel.add(txtInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 260, 51));

        txtAbertura.setEditable(false);
        txtAbertura.setBackground(new java.awt.Color(51, 51, 51));
        txtAbertura.setForeground(new java.awt.Color(240, 240, 240));
        txtAbertura.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtAbertura.setLabel("Horário de Abertura");
        txtAbertura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAberturaFocusGained(evt);
            }
        });
        txtFechamento.setDocument(new LimitText(50));
        formPanel.add(txtAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 260, 51));

        txtEntradas.setEditable(false);
        txtEntradas.setBackground(new java.awt.Color(51, 51, 51));
        txtEntradas.setForeground(new java.awt.Color(240, 240, 240));
        txtEntradas.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtEntradas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtEntradas.setLabel("Entradas");
        txtEntradas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEntradasFocusGained(evt);
            }
        });
        formPanel.add(txtEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 260, 51));

        txtSaidas.setEditable(false);
        txtSaidas.setBackground(new java.awt.Color(51, 51, 51));
        txtSaidas.setForeground(new java.awt.Color(240, 240, 240));
        txtSaidas.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtSaidas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtSaidas.setLabel("Saídas");
        txtSaidas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSaidasFocusGained(evt);
            }
        });
        formPanel.add(txtSaidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 260, 51));

        cardPanel.add(formPanel, "card3");

        bg.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 710, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        if (!txtData1.getText().equals("  /  /    ") && !txtData2.getText().equals("  /  /    ")) {
            menuSelection = 4;
            HashMap<String, Object> parametros = new HashMap();

            parametros.put("data1", txtData1.getText());
            parametros.put("data2", txtData2.getText());
            try {
                cc.gerarRelatorio(parametros, cc.findByDatas(txtData1.getText(), txtData2.getText()), "src/relatorios/Balanco.jrxml");
            } catch (JRException ex) {
                Logger.getLogger(CaixaForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {

            labelWarningData.setText("Digite um período de datas.");
            warningPanelData.setBackground(new Color(255, 51, 51));
            btnMessage.setBackground(new Color(255, 51, 51));
            warningPanelData.setVisible(true);

        }
        voltar();
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageActionPerformed
        warningPanelData.setVisible(false);
    }//GEN-LAST:event_btnMessageActionPerformed

    private void mGradientButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseEntered
        mGradientButton1.setForeground(Color.white);
    }//GEN-LAST:event_mGradientButton1MouseEntered

    private void mGradientButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseExited
        mGradientButton1.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_mGradientButton1MouseExited

    private void mGradientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton1ActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_mGradientButton1ActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new java.awt.Color(230, 230, 230));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorActionPerformed
        warningPanelForm.setVisible(false);
    }//GEN-LAST:event_btnErrorActionPerformed

    private void mButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseEntered
        mButton4.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_mButton4MouseEntered

    private void mButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseExited
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_mButton4MouseExited

    private void mButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton4ActionPerformed

    private void txtFechamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechamentoFocusGained
        txtFechamento.setForeground(new Color(240, 240, 240));
    }//GEN-LAST:event_txtFechamentoFocusGained

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        warningPanelData.setVisible(false);
        warningPanelForm.setVisible(false);
        voltar();
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarActionPerformed
        if (selecionado.getFechamento() == null) {
            Caixa c = ControleCaixa.getCaixa();
            c.setFechamento(new Date());
            ControleCaixa.setCaixa(null);
            cc.alter(c);
        }
    }//GEN-LAST:event_botConfirmarActionPerformed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged

        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
        try {
            setOpacity((float) 0.9);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseReleased

        try {
            setOpacity((float) 1);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseReleased

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFinalFocusGained
        txtValorEstimado.setForeground((new Color(240, 240, 240)));
    }//GEN-LAST:event_txtFinalFocusGained

    private void txtInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInicialFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInicialFocusGained

    private void txtAberturaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAberturaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAberturaFocusGained

    private void txtEntradasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEntradasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEntradasFocusGained

    private void txtSaidasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSaidasFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaidasFocusGained

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        if (menuSelection == 0) {
            if (ControleCaixa.getCaixa() == null) {
                AbreCaixa ac = new AbreCaixa(null, false);
                ac.setVisible(true);
                this.dispose();
            } else {
                menuSelection = 2;
                dataPanel.setVisible(false);
                selecionado = ControleCaixa.getCaixa();
                setCaixa();

                dataPanel.setVisible(false);
                formPanel.setVisible(true);
            }
        } else {
            if (menuSelection == 2) {
                btnFechar.select();
                btnVisualizar.unselect();
            } else if (menuSelection == 3) {
                btnVisualizar.select();
                btnFechar.unselect();
            } else if (menuSelection == 4) {
                btnRelatorio.select();
                btnFechar.unselect();
            }
        }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtData1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtData1FocusGained
        txtData1.setForeground(new Color(240, 240, 240));
        if (txtData1.getText().equals("  /  /    "))
            txtData1.setCaretPosition(0);
    }//GEN-LAST:event_txtData1FocusGained

    private void txtData2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtData2FocusGained
        txtData2.setForeground(new Color(240, 240, 240));
        if (txtData2.getText().equals("  /  /    "))
            txtData2.setCaretPosition(0);
    }//GEN-LAST:event_txtData2FocusGained

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        int linha = tableUsuarios.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um caixa");
        } else {
            selecionado = listaPesquisa.get(linha);
            setCaixa();
            dataPanel.setVisible(false);
            formPanel.setVisible(true);
        }
    }//GEN-LAST:event_btnVisualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code FLAT DARK LAF ">
        try {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CaixaForm dialog = new CaixaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnFechar;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnMessage;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnRelatorio;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton btnVisualizar;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelWarningData;
    private javax.swing.JLabel labelWarningForm;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton4;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton1;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JTable tableUsuarios;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtAbertura;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtData1;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtData2;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtEntradas;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtFechamento;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtFinal;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtInicial;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtSaidas;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtUsuario;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtValorEstimado;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtValorEstimado1;
    private javax.swing.JPanel warningPanelData;
    private javax.swing.JPanel warningPanelForm;
    // End of variables declaration//GEN-END:variables
}
