/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleUsuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.Usuario;
import util.Conversoes;
import util.LimitText;

/**
 *
 * @author Abner
 */
public class UsuarioForm extends javax.swing.JDialog {

    
    private int xMouse, yMouse;
    private Usuario p = new Usuario();
    private ControleUsuario cu = new ControleUsuario();
    private File file;
    private ArrayList<Usuario> listaPesquisa = new ArrayList();
    private Usuario selecionado;
    private int menuSelection = 0;
    private Color errorColor = new Color(255, 0, 0);
    
    public UsuarioForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        warningPanelForm.setVisible(false);
        warningPanelData.setVisible(false);
    }

    private void atualizaTabela() {
        new Thread() {
            @Override
            public void run() {
                listaPesquisa.clear();
                listaPesquisa.addAll(cu.findByNome(txtPesquisa.getText()));
                DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();
                dtm.setNumRows(0);
                for (Usuario s : listaPesquisa) {
                    dtm.addRow(new Object[]{s.getId(), s.getNome(), s.getLogin()});
                }
            }
        }.start();
    }    
    
    private void makeAllBlack() {
        txtNome.setForeground(Color.black);
        txtTelefone.setForeground(Color.black);
        txtNascimento.setForeground(Color.black);
        txtLogin.setForeground(Color.black);
        txtSenha.setForeground(Color.black);
        txtConfirmar.setForeground(Color.black);
        comboTipo.setForeground(new Color(109, 109, 109));
    }
    
    private void limparCampos() {
        txtNome.setText("");
        txtTelefone.setValue("");
        txtNascimento.setValue("");
        txtLogin.setText("");
        txtSenha.setText("");
        txtConfirmar.setText("");
        comboTipo.setSelectedIndex(0);
        
        String imagePath = "/com/hq/swingmaterialdesign/images/profile.jpg";
        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        Image img = icon.getImage();
        profileImagePanel.setImage(img);
        
    }
    
    private void setUsuario() {
        if (selecionado.getFotoPerfil() != null) {
            String imagePath = selecionado.getFotoPerfil();
            ImageIcon im = new ImageIcon(getClass().getResource(imagePath));
            profileImagePanel.setImage(im.getImage());
            profileImagePanel.repaint();
        }
        txtNome.setText(selecionado.getNome());
        txtTelefone.setText(selecionado.getTelefone());
        txtNascimento.setText(Conversoes.getDateToString(selecionado.getDataNascimento()));
        txtLogin.setText(selecionado.getLogin());
        comboTipo.setSelectedIndex(selecionado.getTipo() + 1);
    }
    
    private void voltar() {
        menuSelection = 0;
        addBtn.unselect();;
        changeBtn.unselect();;
        excludeBtn.unselect();
        limparCampos();
        makeAllBlack();
        dataPanel.setVisible(true);
        formPanel.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        excludeBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        addBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        changeBtn = new com.hq.swingmaterialdesign.materialdesign.MToggleButton();
        cardPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        warningPanelData = new javax.swing.JPanel();
        btnMessage = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningData = new javax.swing.JLabel();
        searchPanel = new javax.swing.JPanel();
        txtPesquisa = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        mGradientButton1 = new com.hq.swingmaterialdesign.materialdesign.MGradientButton();
        tablePanel = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        btnExit = new com.hq.swingmaterialdesign.materialdesign.MButton();
        formPanel = new javax.swing.JPanel();
        warningPanelForm = new javax.swing.JPanel();
        btnError = new com.hq.swingmaterialdesign.materialdesign.MButton();
        labelWarningForm = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mButton4 = new com.hq.swingmaterialdesign.materialdesign.MButton();
        txtNome = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        botCancelar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        botConfirmar = new com.hq.swingmaterialdesign.materialdesign.MButton();
        profileImagePanel = new com.hq.swingmaterialdesign.materialdesign.MGradientPanel();
        labelImagem = new javax.swing.JLabel();
        txtNascimento = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtTelefone = new com.hq.swingmaterialdesign.materialdesign.MFormattedTextField();
        txtLogin = new com.hq.swingmaterialdesign.materialdesign.MTextField();
        txtSenha = new com.hq.swingmaterialdesign.materialdesign.MPasswordField();
        txtConfirmar = new com.hq.swingmaterialdesign.materialdesign.MPasswordField();
        comboTipo = new com.hq.swingmaterialdesign.materialdesign.MComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bgMouseReleased(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(24, 24, 24));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUÁRIO");
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 26, 230, 40));

        excludeBtn.setBackground(new java.awt.Color(24, 24, 24));
        excludeBtn.setBorder(null);
        excludeBtn.setForeground(new java.awt.Color(255, 255, 255));
        excludeBtn.setText("Excluir");
        excludeBtn.setEndColor(new java.awt.Color(24, 24, 24));
        excludeBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        excludeBtn.setHoverEndColor(new java.awt.Color(24, 24, 24));
        excludeBtn.setHoverStartColor(new java.awt.Color(37, 46, 55));
        excludeBtn.setSelectedColor(new java.awt.Color(50, 56, 68));
        excludeBtn.setStartColor(new java.awt.Color(24, 24, 24));
        excludeBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        excludeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excludeBtnActionPerformed(evt);
            }
        });
        sidePanel.add(excludeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        addBtn.setBackground(new java.awt.Color(24, 24, 24));
        addBtn.setBorder(null);
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Adicionar");
        addBtn.setEndColor(new java.awt.Color(24, 24, 24));
        addBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        addBtn.setHoverEndColor(new java.awt.Color(24, 24, 24));
        addBtn.setHoverStartColor(new java.awt.Color(37, 46, 55));
        addBtn.setSelectedColor(new java.awt.Color(50, 56, 68));
        addBtn.setStartColor(new java.awt.Color(24, 24, 24));
        addBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        sidePanel.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        changeBtn.setBackground(new java.awt.Color(24, 24, 24));
        changeBtn.setBorder(null);
        changeBtn.setForeground(new java.awt.Color(255, 255, 255));
        changeBtn.setText("Alterar");
        changeBtn.setEndColor(new java.awt.Color(24, 24, 24));
        changeBtn.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        changeBtn.setHoverEndColor(new java.awt.Color(24, 24, 24));
        changeBtn.setHoverStartColor(new java.awt.Color(37, 46, 55));
        changeBtn.setSelectedColor(new java.awt.Color(50, 56, 68));
        changeBtn.setStartColor(new java.awt.Color(24, 24, 24));
        changeBtn.setType(com.hq.swingmaterialdesign.materialdesign.MToggleButton.Type.FLAT);
        changeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBtnActionPerformed(evt);
            }
        });
        sidePanel.add(changeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 580));

        cardPanel.setLayout(new java.awt.CardLayout());

        dataPanel.setBackground(new java.awt.Color(51, 51, 51));
        dataPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelData.setBackground(new java.awt.Color(0, 153, 0));

        btnMessage.setBackground(new java.awt.Color(0, 153, 0));
        btnMessage.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnMessage.setBorderRadius(0);
        btnMessage.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnMessage.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessageActionPerformed(evt);
            }
        });

        labelWarningData.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningData.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningData.setText("Cadastro efetuado com sucesso.");

        javax.swing.GroupLayout warningPanelDataLayout = new javax.swing.GroupLayout(warningPanelData);
        warningPanelData.setLayout(warningPanelDataLayout);
        warningPanelDataLayout.setHorizontalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelDataLayout.createSequentialGroup()
                .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelDataLayout.setVerticalGroup(
            warningPanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        dataPanel.add(warningPanelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        searchPanel.setBackground(new java.awt.Color(24, 24, 24));

        txtPesquisa.setBackground(new java.awt.Color(24, 24, 24));
        txtPesquisa.setForeground(new java.awt.Color(240, 240, 240));
        txtPesquisa.setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        txtPesquisa.setLabel("Pesquisar");
        txtPesquisa.setSelectionColor(new java.awt.Color(0, 153, 153));

        mGradientButton1.setForeground(new java.awt.Color(204, 204, 204));
        mGradientButton1.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.SEARCH));
        mGradientButton1.setBorderRadius(58);
        mGradientButton1.setEndColor(new java.awt.Color(24, 24, 24));
        mGradientButton1.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(26f));
        mGradientButton1.setHoverEndColor(new java.awt.Color(24, 24, 24));
        mGradientButton1.setHoverStartColor(new java.awt.Color(24, 24, 24));
        mGradientButton1.setStartColor(new java.awt.Color(24, 24, 24));
        mGradientButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mGradientButton1MouseExited(evt);
            }
        });
        mGradientButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGradientButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(9, 9, 9)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mGradientButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        dataPanel.add(searchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 710, 100));

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePanel.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tablePanel.setHorizontalScrollBar(null);

        tableUsuarios.setBackground(new java.awt.Color(51, 51, 51));
        tableUsuarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableUsuarios.setFont(new java.awt.Font("Nunito SemiBold", 0, 14)); // NOI18N
        tableUsuarios.setForeground(new java.awt.Color(72, 72, 72));
        tableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Tipo", "Nome de Usuário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        tableUsuarios.setRowHeight(30);
        tableUsuarios.setSelectionBackground(new java.awt.Color(205, 205, 205));
        tablePanel.setViewportView(tableUsuarios);
        tableUsuarios.getTableHeader().setFont(new java.awt.Font("Nunito Bold", 0, 14));

        dataPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 670, 390));

        btnExit.setBackground(new java.awt.Color(51, 51, 51));
        btnExit.setBorder(null);
        btnExit.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnExit.setBorderRadius(0);
        btnExit.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnExit.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        dataPanel.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 50, 40));

        cardPanel.add(dataPanel, "card2");

        formPanel.setBackground(new java.awt.Color(51, 51, 51));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        warningPanelForm.setBackground(new java.awt.Color(255, 51, 51));

        btnError.setBackground(new java.awt.Color(255, 51, 51));
        btnError.setBorder(null);
        btnError.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        btnError.setBorderRadius(0);
        btnError.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        btnError.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        btnError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnErrorActionPerformed(evt);
            }
        });

        labelWarningForm.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        labelWarningForm.setForeground(new java.awt.Color(255, 255, 255));
        labelWarningForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarningForm.setText("Preencha os campos corretamente.");

        javax.swing.GroupLayout warningPanelFormLayout = new javax.swing.GroupLayout(warningPanelForm);
        warningPanelForm.setLayout(warningPanelFormLayout);
        warningPanelFormLayout.setHorizontalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningPanelFormLayout.createSequentialGroup()
                .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        warningPanelFormLayout.setVerticalGroup(
            warningPanelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelWarningForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnError, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanel.add(warningPanelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 710, 40));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        mButton4.setBackground(new java.awt.Color(102, 102, 102));
        mButton4.setBorder(null);
        mButton4.setText(String.valueOf(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.CLOSE));
        mButton4.setBorderRadius(0);
        mButton4.setFont(com.hq.swingmaterialdesign.materialdesign.resource.MaterialIcons.ICON_FONT.deriveFont(20f));
        mButton4.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.FLAT);
        mButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mButton4MouseExited(evt);
            }
        });
        mButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        formPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));

        txtNome.setBackground(new java.awt.Color(51, 51, 51));
        txtNome.setForeground(new java.awt.Color(240, 240, 240));
        txtNome.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtNome.setLabel("Nome");
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });
        txtNome.setDocument(new LimitText(50));
        formPanel.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 370, 51));

        botCancelar.setBackground(new java.awt.Color(102, 102, 102));
        botCancelar.setBorder(null);
        botCancelar.setText("CANCELAR");
        botCancelar.setBorderRadius(50);
        botCancelar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botCancelar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCancelarActionPerformed(evt);
            }
        });
        formPanel.add(botCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 514, 180, 50));

        botConfirmar.setBackground(new java.awt.Color(153, 153, 153));
        botConfirmar.setBorder(null);
        botConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        botConfirmar.setText("Confirmar");
        botConfirmar.setBorderRadius(50);
        botConfirmar.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        botConfirmar.setType(com.hq.swingmaterialdesign.materialdesign.MButton.Type.RAISED);
        botConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botConfirmarActionPerformed(evt);
            }
        });
        formPanel.add(botConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 514, 180, 50));

        profileImagePanel.setBackground(new java.awt.Color(51, 51, 51));
        profileImagePanel.setBorderRadius(120);
        profileImagePanel.setFillBackground(false);
        profileImagePanel.setFillImage(true);
        profileImagePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileImagePanelMouseEntered(evt);
            }
        });

        labelImagem.setBackground(new java.awt.Color(51, 51, 51));
        labelImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelImagemMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelImagemMouseExited(evt);
            }
        });

        javax.swing.GroupLayout profileImagePanelLayout = new javax.swing.GroupLayout(profileImagePanel);
        profileImagePanel.setLayout(profileImagePanelLayout);
        profileImagePanelLayout.setHorizontalGroup(
            profileImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profileImagePanelLayout.setVerticalGroup(
            profileImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        formPanel.add(profileImagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 120, 120));

        txtNascimento.setBackground(new java.awt.Color(51, 51, 51));
        txtNascimento.setForeground(new java.awt.Color(240, 240, 240));
        txtNascimento.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.setLabel("Data de Nascimento");
        txtNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNascimentoFocusGained(evt);
            }
        });
        formPanel.add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 155, 51));

        txtTelefone.setBackground(new java.awt.Color(51, 51, 51));
        txtTelefone.setForeground(new java.awt.Color(240, 240, 240));
        txtTelefone.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setLabel("Telefone");
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusGained(evt);
            }
        });
        formPanel.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 200, 51));

        txtLogin.setBackground(new java.awt.Color(51, 51, 51));
        txtLogin.setForeground(new java.awt.Color(240, 240, 240));
        txtLogin.setFont(new java.awt.Font("Nunito", 0, 16)); // NOI18N
        txtLogin.setLabel("Nome de usuário");
        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginFocusGained(evt);
            }
        });
        txtLogin.setDocument(new LimitText(10));
        formPanel.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 200, 50));

        txtSenha.setBackground(new java.awt.Color(51, 51, 51));
        txtSenha.setForeground(new java.awt.Color(240, 240, 240));
        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSenha.setLabel("Senha");
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
        });
        txtSenha.setDocument(new LimitText(10));
        formPanel.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 160, 50));

        txtConfirmar.setBackground(new java.awt.Color(51, 51, 51));
        txtConfirmar.setForeground(new java.awt.Color(240, 240, 240));
        txtConfirmar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtConfirmar.setLabel("Confirmar Senha");
        txtConfirmar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmarFocusGained(evt);
            }
        });
        txtConfirmar.setDocument(new LimitText(10));
        formPanel.add(txtConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 145, 50));

        comboTipo.setBackground(new java.awt.Color(51, 51, 51));
        comboTipo.setBorder(null);
        comboTipo.setForeground(new java.awt.Color(153, 153, 153));
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o tipo de acesso", "Tatuador", "Secretario" }));
        comboTipo.setAccent(new java.awt.Color(0, 188, 212));
        comboTipo.setFont(new java.awt.Font("Nunito", 0, 11)); // NOI18N
        comboTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboTipoFocusGained(evt);
            }
        });
        formPanel.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 210, 50));

        cardPanel.add(formPanel, "card3");

        bg.add(cardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 710, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excludeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excludeBtnActionPerformed
        int linha = tableUsuarios.getSelectedRow();
        int codigo;
        Usuario sExcluir = null;
        if (menuSelection == 0) {

            if (linha != -1) {
                menuSelection = 3;
                int colunas = tableUsuarios.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableUsuarios.getColumnName(x).equals("Código")) {
                        codigo = (int) tableUsuarios.getValueAt(linha, x);
                        sExcluir = cu.findById(codigo);

                    }
                }
                if (sExcluir != null) {
                    int op = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir " + sExcluir.getNome() + "?");
                    if (op == 0) {
                        try {
                            cu.delete(sExcluir);
                            DefaultTableModel dtm = (DefaultTableModel) tableUsuarios.getModel();
                            dtm.removeRow(linha);
                            warningPanelData.setVisible(true);
                            warningPanelData.setBackground(new Color(0, 153, 0));
                            btnMessage.setBackground(new Color(0, 153, 0));
                            labelWarningData.setText("Excluído com sucesso!");
                            menuSelection = 0;

                        } catch (Exception e) {
                            warningPanelData.setVisible(true);
                            warningPanelData.setBackground(new Color(255, 51, 51));
                            btnMessage.setBackground(new Color(255, 51, 51));
                            labelWarningData.setText("Este secretário possui registros vinculados.\nNão foi possível realizar a exclusão!");
                            menuSelection = 0;
                        }
                    }

                }

            } else {
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                labelWarningData.setText("Selecione um secretário.");
            }
        } else {
            if (menuSelection == 1) {
                addBtn.select();
                excludeBtn.unselect();
            } else if (menuSelection==2){
                changeBtn.select();
                excludeBtn.unselect();
            }
        }
    }//GEN-LAST:event_excludeBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (menuSelection == 0) {
            p = new Usuario();
            selecionado =null;
            menuSelection = 1;
            dataPanel.setVisible(false);
            formPanel.setVisible(true);
            selecionado = null;
            limparCampos();
        } else {
            if (menuSelection==2){
                changeBtn.select();
                addBtn.unselect();
            }else if(menuSelection==3){
                excludeBtn.select();
                addBtn.unselect();
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void changeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBtnActionPerformed
        if (menuSelection == 0) {
            int linha = tableUsuarios.getSelectedRow();
            int codigo;
            if (linha != -1) {
                menuSelection = 2;
                int colunas = tableUsuarios.getColumnCount();
                for (int x = 0; x < colunas; x++) {
                    if (tableUsuarios.getColumnName(x).equals("Código")) {
                        codigo = (int) tableUsuarios.getValueAt(linha, x);
                        selecionado = cu.findById(codigo);
                        setUsuario();
                        dataPanel.setVisible(false);
                        formPanel.setVisible(true);
                    }
                }

            } else {
                changeBtn.unselect();
                labelWarningData.setText("Selecione um secretário.");
                warningPanelData.setVisible(true);
                warningPanelData.setBackground(new Color(255, 51, 51));
                btnMessage.setBackground(new Color(255, 51, 51));
                menuSelection = 0;
                //timer
            }
        } else {
            if (menuSelection == 1) {
                addBtn.select();
                changeBtn.unselect();
            } else if (menuSelection==3){
                excludeBtn.select();
                changeBtn.unselect();
            }
        }
    }//GEN-LAST:event_changeBtnActionPerformed

    private void btnMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessageActionPerformed
        warningPanelData.setVisible(false);
    }//GEN-LAST:event_btnMessageActionPerformed

    private void mGradientButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseEntered
        mGradientButton1.setForeground(Color.white);
    }//GEN-LAST:event_mGradientButton1MouseEntered

    private void mGradientButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mGradientButton1MouseExited
        mGradientButton1.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_mGradientButton1MouseExited

    private void mGradientButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGradientButton1ActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_mGradientButton1ActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnErrorActionPerformed
        warningPanelForm.setVisible(false);
    }//GEN-LAST:event_btnErrorActionPerformed

    private void mButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseEntered
        mButton4.setForeground(new java.awt.Color(50, 60, 69));
    }//GEN-LAST:event_mButton4MouseEntered

    private void mButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mButton4MouseExited
        mButton4.setForeground(new java.awt.Color(153, 153, 153));
    }//GEN-LAST:event_mButton4MouseExited

    private void mButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_mButton4ActionPerformed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setForeground(Color.black);
    }//GEN-LAST:event_txtNomeFocusGained

    private void botCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCancelarActionPerformed
        warningPanelData.setVisible(false);
        warningPanelForm.setVisible(false);
        voltar();
    }//GEN-LAST:event_botCancelarActionPerformed

    private void botConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botConfirmarActionPerformed
        byte[] imageInByte = null;

        if (file != null) {
            imageInByte = new byte[(int) file.length()];
            FileInputStream fis = null;
            try {
                fis = new FileInputStream(file);
                fis.read(imageInByte);
                fis.close();
            } catch (IOException ex) {
                Logger.getLogger(UsuarioForm.class.getName()).log(Level.SEVERE, null, ex);
                fis = null;
            }
        }
        boolean flag = false;
        String message = "";
        boolean passerr = false;
        if (comboTipo.getSelectedIndex() == 0) {
            comboTipo.setForeground(new Color(255, 102, 102));
            flag = true;
        }

        if (txtNome.getText().equals("")) {
            txtNome.setForeground(errorColor);
            flag = true;
        }
        if (txtTelefone.getText().equals("(  )      -    ")) {
            txtTelefone.setForeground(errorColor);
            flag = true;
        }
        if (txtNascimento.getText().equals("  /  /    ")) {
            txtNascimento.setForeground(errorColor);
            flag = true;
        }
        
        if (txtLogin.getText().equals("")) {
            txtLogin.setForeground(errorColor);
            flag = true;
        }
        if (txtSenha.getText().equals("")) {
            txtSenha.setForeground(errorColor);
            flag = true;
        }
        if (txtSenha.getPassword().length < 4) {
            txtSenha.setForeground(errorColor);
            passerr = true;
        }
        if (txtConfirmar.getText().equals("")) {
            txtConfirmar.setForeground(errorColor);
            flag = true;
        }

        this.repaint();

        if (flag) {
            message = "Preencha todos os campos corretamente.";

        }
        if (passerr) {
            message += " A senha deve ter no mínimo 4 caracteres!";

        }
        if (!txtSenha.getText().equals(txtConfirmar.getText()) && !passerr) {
            txtSenha.setForeground(errorColor);
            message += " As senhas não correspondem";
            flag = true;
        }

        if (!flag && !passerr) {
            p.setNome(txtNome.getText());
            p.setDataNascimento(Conversoes.getStringToDate(txtNascimento.getText()));
            p.setLogin(txtLogin.getText());
            p.setSenha(txtSenha.getText());
            p.setTelefone(txtTelefone.getText());

            p.setTipo(comboTipo.getSelectedIndex() - 1);

            if (file != null) {
                File outputfile = new File((new Date()).toString() + ".jpg");
                p.setFotoPerfil("/view/images/" + outputfile);
                Image img = null;
                try {
                    img = ImageIO.read(file);
                    ImageIO.write((RenderedImage) img, "png", outputfile);
                } catch (IOException ex) {
                    Logger.getLogger(UsuarioForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (selecionado == null) {
                try {

                    cu.persist(p);
                    message = "Cadastro efetuado com sucesso.";
                    warningPanelData.setBackground(new Color(0, 153, 0));
                    btnMessage.setBackground(new Color(0, 153, 0));
                    warningPanelData.setVisible(true);
                    limparCampos();
                    labelWarningData.setText(message);
                    warningPanelData.setVisible(true);
                    voltar();
                } catch (Exception ex) {
                    message = "Login ou cpf ja cadastrado.";
                    txtLogin.requestFocus();
                    txtLogin.setForeground(errorColor);

                    warningPanelForm.setBackground(new Color(255, 51, 51));
                    btnError.setBackground(new Color(255, 51, 51));
                    labelWarningForm.setText(message);
                    warningPanelForm.setVisible(true);

                }
            } else {
                p.setId(selecionado.getId());
                cu.alter(p);
                message = "Alteração efetuada com sucesso.";
                warningPanelData.setBackground(new Color(0, 153, 0));
                btnMessage.setBackground(new Color(0, 153, 0));
                labelWarningData.setText(message);
                warningPanelData.setVisible(true);
                voltar();
            }

            //timer
            // view panel aviso, setColor aviso (danger/success) -> flag , setText(message)
        } else {

            labelWarningForm.setText(message);
            warningPanelForm.setVisible(true);
            warningPanelForm.setBackground(new Color(255, 51, 51));
            btnError.setBackground(new Color(255, 51, 51));

        }
    }//GEN-LAST:event_botConfirmarActionPerformed

    private void labelImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImagemMouseClicked
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecione a imagem de perfil");
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        FileNameExtensionFilter ext = new FileNameExtensionFilter("Imagem", "png", "jpg", "bmp");

        jfc.setFileFilter(ext);

        int r = jfc.showOpenDialog(this);

        if (r == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            Image image = null;
            try {
                image = ImageIO.read(file);

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Impossível carregar imagem!");
            } finally {
                System.out.println(file.getAbsolutePath());
                profileImagePanel.setImage(image);
                profileImagePanel.repaint();
            }
        }
    }//GEN-LAST:event_labelImagemMouseClicked

    private void labelImagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelImagemMouseExited
        labelImagem.setVisible(false);
    }//GEN-LAST:event_labelImagemMouseExited

    private void profileImagePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileImagePanelMouseEntered
        labelImagem.setVisible(true);
    }//GEN-LAST:event_profileImagePanelMouseEntered

    private void txtNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNascimentoFocusGained
        txtNascimento.setForeground(Color.black);
        if (txtNascimento.getText().equals("  /  /    "))
        txtNascimento.setCaretPosition(0);
    }//GEN-LAST:event_txtNascimentoFocusGained

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        txtTelefone.setForeground(Color.black);
    }//GEN-LAST:event_txtTelefoneFocusGained

    private void txtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusGained
        txtLogin.setForeground(Color.black);
    }//GEN-LAST:event_txtLoginFocusGained

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        txtSenha.setForeground(Color.black);
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtConfirmarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmarFocusGained
        txtConfirmar.setForeground(Color.black);
    }//GEN-LAST:event_txtConfirmarFocusGained

    private void comboTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboTipoFocusGained
        comboTipo.setForeground(new Color(109, 109, 109));
    }//GEN-LAST:event_comboTipoFocusGained

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged

        setLocation(evt.getXOnScreen() - xMouse, evt.getYOnScreen() - yMouse);
        try {
            setOpacity((float) 0.9);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseReleased

        try {
            setOpacity((float) 1);
        } catch (java.lang.UnsupportedOperationException e) {

        }
    }//GEN-LAST:event_bgMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UsuarioForm dialog = new UsuarioForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton addBtn;
    private javax.swing.JPanel bg;
    private com.hq.swingmaterialdesign.materialdesign.MButton botCancelar;
    private com.hq.swingmaterialdesign.materialdesign.MButton botConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnError;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnExit;
    private com.hq.swingmaterialdesign.materialdesign.MButton btnMessage;
    private javax.swing.JPanel cardPanel;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton changeBtn;
    private com.hq.swingmaterialdesign.materialdesign.MComboBox comboTipo;
    private javax.swing.JPanel dataPanel;
    private com.hq.swingmaterialdesign.materialdesign.MToggleButton excludeBtn;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel labelWarningData;
    private javax.swing.JLabel labelWarningForm;
    private com.hq.swingmaterialdesign.materialdesign.MButton mButton4;
    private com.hq.swingmaterialdesign.materialdesign.MGradientButton mGradientButton1;
    private com.hq.swingmaterialdesign.materialdesign.MGradientPanel profileImagePanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JTable tableUsuarios;
    private com.hq.swingmaterialdesign.materialdesign.MPasswordField txtConfirmar;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtLogin;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtNascimento;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtNome;
    private com.hq.swingmaterialdesign.materialdesign.MTextField txtPesquisa;
    private com.hq.swingmaterialdesign.materialdesign.MPasswordField txtSenha;
    private com.hq.swingmaterialdesign.materialdesign.MFormattedTextField txtTelefone;
    private javax.swing.JPanel warningPanelData;
    private javax.swing.JPanel warningPanelForm;
    // End of variables declaration//GEN-END:variables
}
